production: &production_settings
  # Site ID zero means admin site - allow access to all pages, etc.
  SITE_ID: 0
  ROOT: 'http://localhost:3000'
  LAYOUT: 'admin'
  TITLE: 'Wayground Dev'
  TITLE_PREFIX: 'WG Dev'
  TITLE_SHORT: 'WG'
  SENDER: 'Wayground <wayground@wayground.ca>'
  EMAIL: 'wayground@wayground.ca'
  DEFAULT_DOMAIN: 'wayground.ca'
  RESERVED_SUBPATHS: ["index", "show", "list", "new", "create", "edit", "update", "destroy", "delete", "search", "about", "addresses", "admin", "archive", "archives", "attachments", "bin", "blogs", "boards", "calendar", "calendars", "campaigns", "candidates", "categories", "chunks", "classified", "classifieds", "comments", "contacts", "description", "docs", "documents", "elections", "emails", "events", "files", "forums", "functions", "groups", "images", "layouts", "levels", "links", "listings", "locations", "media", "members", "memberships", "messages", "news", "offices", "pages", "parties", "paths", "petitions", "photos", "pics", "pictures", "podcasts", "policies", "polls", "ratings", "replies", "resources", "rss", "rsvp", "rsvps", "schedules", "signatures", "surveys", "tag", "tags", "topics", "trash", "users", "videos", "vids", "votes", "weblinks", "welcome", "wiki"]

development:
  <<: *production_settings

test:
  SITE_ID: 0
  ROOT: 'http://wayground.ca'
  LAYOUT: 'admin'
  TITLE: 'Wayground'
  TITLE_PREFIX: 'Wayground'
  TITLE_SHORT: 'WG'
  SENDER: 'Wayground <wayground@wayground.ca>'
  EMAIL: 'wayground@wayground.ca'
  DEFAULT_DOMAIN: 'wayground.ca'
  RESERVED_SUBPATHS: ["index", "show", "list", "new", "create", "edit", "update", "destroy", "delete", "search", "about", "addresses", "admin", "archive", "archives", "attachments", "bin", "blogs", "boards", "calendar", "calendars", "campaigns", "candidates", "categories", "chunks", "classified", "classifieds", "comments", "contacts", "description", "docs", "documents", "elections", "emails", "events", "files", "forums", "functions", "groups", "images", "layouts", "levels", "links", "listings", "locations", "media", "members", "memberships", "messages", "news", "offices", "pages", "parties", "paths", "petitions", "photos", "pics", "pictures", "podcasts", "policies", "polls", "ratings", "replies", "resources", "rss", "rsvp", "rsvps", "schedules", "signatures", "surveys", "tag", "tags", "topics", "trash", "users", "videos", "vids", "votes", "weblinks", "welcome", "wiki"]
