# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

# WAYGROUND SETUP:
# You can change these setting however you choose.
# You will at least want to set the values of username, password and secret.
# Secret can be quite long (>128 chars) and should be just letters and numbers.

development:
  adapter: mysql
  database: wayground
  username: 
  password: 
  host: localhost
  #port: 3306
  socket: /tmp/mysql.sock
  encoding: utf8
  session_key: _wayground_session
	secret: 

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  database: test
  username: 
  password: 
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
  session_key: _wayground_test
	secret: 
  # alternate:
  #adapter: sqlite3
  #database: db/test.sqlite3
  #timeout: 5000

production:
  development
