require 'iconv'
class Tag < ActiveRecord::Base
	attr_accessible :title
	
	validates_presence_of :title
	validates_presence_of :tag
	validates_format_of :tag, :with=>/\A([a-z0-9]+)\z/
	validates_uniqueness_of :tag, :scope=>[:item_type, :item_id]
	
	belongs_to :item, :polymorphic=>true
	belongs_to :user
	
	def title=(t)
		write_attribute('title', t)
		# tag is generated by transliterating utf-8 characters to ascii,
		# converting letters to lower-case,
		# and stripping everything except letters and numbers
		tag = Iconv.iconv('ASCII//TRANSLIT', 'UTF-8', t).to_s.downcase.gsub(/[^a-z0-9]+/, '')
		write_attribute('tag', tag)
	end
end
